// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kegshneqtyopntlbapst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlZ3NobmVxdHlvcG50bGJhcHN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4NDkwODYsImV4cCI6MjA0OTQyNTA4Nn0.2L2xX8OUM1fy-vLRd0uaaDSNEUbWp8xrqYzLAV2Bngw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);